---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  # prefer brew ansible
  - ansible
  # development
  - git
  - python
  - fabric
  - npm
  # nice to have
  - openssl
  - pv

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/dupes

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # essentials
  - dropbox
  - firefox
  - google-chrome
  - zoom
  - 1password
  - iterm2
  # extras
  - licecap
  - skitch
  # editor
  - emacs
  - slack
  # basic dev
  - vagrant
  - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""
